//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingYourPackage.Domain.Data.Models
{
    using PingYourPackage.Domain.Data.Contracts;
    using System;
    using System.Collections.Generic;

    public partial class PackageReceiver : IEntity
    {
        public PackageReceiver()
        {
            this.Shipments = new HashSet<Shipment>();
        }

        public int Id { get; set; }
        public int ReceiverNbr { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
