//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingYourPackage.Domain.Data.Models
{
    using PingYourPackage.Domain.Data.Contracts;
    using System;
    using System.Collections.Generic;

    public partial class ShipmentType : IEntity
    {
        public ShipmentType()
        {
            this.Shipments = new HashSet<Shipment>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
